### PR TITLE
upgrade httptools to avoid local build

### LINKED ISSUE #2: upgrade httptools to newest version
Please upgrade httptools to the latest version to avoid encountering this error when building httptools locally:
```
      httptools/parser/parser.c:212:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```
because the latest httptools comes with wheel files that provides support for most python3 versions.

### PR DESCRIPTION
**Pull request by xyb**
fix #2

### CODE REVIEW

**Comment by xyb** [comment]
@PeterDing gentle ping

**Comment by xyb** [comment]
gently ping

**Comment by PeterDing** [comment]
Can you update `httptools` to the last version `^0.6.1`.

**Comment by xyb** [comment]
@PeterDing updated

**Comment by PeterDing** [comment]
Thanks your contribution!

**Pull request merged**
